#!/bin/bash

# run arx tests

ARX=1
SNAP=0
if [[ $ARX == 1 ]]; then
#    pytest -m 'chanshort'
    pytest -m 'chanpower' test_arx.py
    pytest -m 'chancurrent' test_arx.py
    pytest -m 'chanvoltage' test_arx.py
    pytest -m 'allchanpower' test_arx.py
    pytest -m 'allchancurrent' test_arx.py
    pytest -m 'badchannel' test_arx.py
    pytest -m 'serial7' test_arx.py
    pytest -m 'serial8' test_arx.py
    pytest -m 'serial6' test_arx.py
fi

# SNAP tests
if [[ $SNAP == 1 ]]; then
   pytest -m "snapserial0"
   pytest -m "snapserial0"
   pytest -m "snapserial"
fi
