#!/bin/bash

# run arx tests

ARX=0
SNAP=1
if [[ $ARX == 1 ]]; then
    pytest -m 'serial0'
    pytest -m 'serial1'
    pytest -m 'serial2'
    pytest -m 'serial3'
    pytest -m 'serial4'
    pytest -m 'serial5'
    pytest -m 'serial6'
    pytest -m 'serial7'
    pytest -m 'serial8'
    pytest -m 'serial9'
    pytest -m 'fatten'
    pytest -m 'satten'
    pytest -m 'sattenARX'
    pytest -m 'fattenARX'
    pytest -m 'serialLPNARX'
    pytest -m 'serialLPWARX'
fi

# SNAP tests
if [[ $SNAP == 1 ]]; then
   pytest -m "snapserial0"
   pytest -m "snapserial0"
   pytest -m "snapserial"
fi
